import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { ExplorerBar, FileBar } from "@/app/_components";

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-jetbrains",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${jetbrainsMono.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <div className="lg:flex">
          <ExplorerBar />

          <main className="flex-1 min-w-0 flex flex-col bg-bg-main">
            <FileBar />

            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
